--------------------------------------------------------
--  File created - Sunday-June-23-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FLIGHT
--------------------------------------------------------

  CREATE TABLE "FLIGHT" 
   (	"FLIGHT_ID" VARCHAR2(50 BYTE), 
	"FLIGHT_TYPE" VARCHAR2(50 BYTE), 
	"SEATS" NUMBER, 
	"FLIGHT_WEIGHT" NUMBER, 
	"E_SEATS" NUMBER(3,0), 
	"B_SEATS" NUMBER(3,0), 
	"F_SEATS" NUMBER(3,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into FLIGHT
SET DEFINE OFF;
Insert into FLIGHT (FLIGHT_ID,FLIGHT_TYPE,SEATS,FLIGHT_WEIGHT,E_SEATS,B_SEATS,F_SEATS) values ('1A 6144','DOMESTIC',150,50,75,50,25);
Insert into FLIGHT (FLIGHT_ID,FLIGHT_TYPE,SEATS,FLIGHT_WEIGHT,E_SEATS,B_SEATS,F_SEATS) values ('7F 6211','INTERNATIONAL',200,100,75,75,50);
Insert into FLIGHT (FLIGHT_ID,FLIGHT_TYPE,SEATS,FLIGHT_WEIGHT,E_SEATS,B_SEATS,F_SEATS) values ('2A 3412','DOMESTIC',125,40,50,50,25);
Insert into FLIGHT (FLIGHT_ID,FLIGHT_TYPE,SEATS,FLIGHT_WEIGHT,E_SEATS,B_SEATS,F_SEATS) values ('7B 4764','DOMESTIC',150,50,75,50,25);
Insert into FLIGHT (FLIGHT_ID,FLIGHT_TYPE,SEATS,FLIGHT_WEIGHT,E_SEATS,B_SEATS,F_SEATS) values ('5A 2141','INTERNATIONAL',200,100,75,75,50);
Insert into FLIGHT (FLIGHT_ID,FLIGHT_TYPE,SEATS,FLIGHT_WEIGHT,E_SEATS,B_SEATS,F_SEATS) values ('3C 5271','DOMESTIC',150,40,75,50,25);
Insert into FLIGHT (FLIGHT_ID,FLIGHT_TYPE,SEATS,FLIGHT_WEIGHT,E_SEATS,B_SEATS,F_SEATS) values ('6F 5648','DOMESTIC',150,50,75,50,25);
Insert into FLIGHT (FLIGHT_ID,FLIGHT_TYPE,SEATS,FLIGHT_WEIGHT,E_SEATS,B_SEATS,F_SEATS) values ('3A 3909','DOMESTIC',150,50,75,50,25);
Insert into FLIGHT (FLIGHT_ID,FLIGHT_TYPE,SEATS,FLIGHT_WEIGHT,E_SEATS,B_SEATS,F_SEATS) values ('3A 7604','INTERNATIONAL',200,250,100,70,30);
