--------------------------------------------------------
--  File created - Sunday-June-23-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table LUGGAGE_CAPACITY
--------------------------------------------------------

  CREATE TABLE "LUGGAGE_CAPACITY" 
   (	"FLIGHT_ID" VARCHAR2(50 BYTE), 
	"E_CAPACITY" NUMBER(3,0), 
	"B_CAPACITY" NUMBER(3,0), 
	"F_CAPACITY" NUMBER(3,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into LUGGAGE_CAPACITY
SET DEFINE OFF;
Insert into LUGGAGE_CAPACITY (FLIGHT_ID,E_CAPACITY,B_CAPACITY,F_CAPACITY) values ('1A 6144',13,16,20);
Insert into LUGGAGE_CAPACITY (FLIGHT_ID,E_CAPACITY,B_CAPACITY,F_CAPACITY) values ('2A 3412',15,15,20);
Insert into LUGGAGE_CAPACITY (FLIGHT_ID,E_CAPACITY,B_CAPACITY,F_CAPACITY) values ('3C 5271',13,16,20);
Insert into LUGGAGE_CAPACITY (FLIGHT_ID,E_CAPACITY,B_CAPACITY,F_CAPACITY) values ('5A 2141',20,25,30);
Insert into LUGGAGE_CAPACITY (FLIGHT_ID,E_CAPACITY,B_CAPACITY,F_CAPACITY) values ('7B 4764',13,14,20);
Insert into LUGGAGE_CAPACITY (FLIGHT_ID,E_CAPACITY,B_CAPACITY,F_CAPACITY) values ('7F 6211',20,25,30);
