--------------------------------------------------------
--  File created - Sunday-June-23-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PERMIT
--------------------------------------------------------

  CREATE TABLE "PERMIT" 
   (	"TRIP_ID" NUMBER(3,0), 
	"AIRPORT_AUTHORITY" VARCHAR2(50 BYTE), 
	"DEPARTURE_TERMINAL" NUMBER(2,0), 
	"ARRIVAL_TERMINAL" NUMBER(2,0), 
	"GATE_NO" NUMBER(2,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into PERMIT
SET DEFINE OFF;
Insert into PERMIT (TRIP_ID,AIRPORT_AUTHORITY,DEPARTURE_TERMINAL,ARRIVAL_TERMINAL,GATE_NO) values (111,'yes',4,5,23);
Insert into PERMIT (TRIP_ID,AIRPORT_AUTHORITY,DEPARTURE_TERMINAL,ARRIVAL_TERMINAL,GATE_NO) values (112,'yes',13,10,14);
Insert into PERMIT (TRIP_ID,AIRPORT_AUTHORITY,DEPARTURE_TERMINAL,ARRIVAL_TERMINAL,GATE_NO) values (113,'no',5,4,32);
Insert into PERMIT (TRIP_ID,AIRPORT_AUTHORITY,DEPARTURE_TERMINAL,ARRIVAL_TERMINAL,GATE_NO) values (114,'yes',2,8,12);
Insert into PERMIT (TRIP_ID,AIRPORT_AUTHORITY,DEPARTURE_TERMINAL,ARRIVAL_TERMINAL,GATE_NO) values (115,'yes',7,2,16);
Insert into PERMIT (TRIP_ID,AIRPORT_AUTHORITY,DEPARTURE_TERMINAL,ARRIVAL_TERMINAL,GATE_NO) values (116,'yes',3,1,4);
Insert into PERMIT (TRIP_ID,AIRPORT_AUTHORITY,DEPARTURE_TERMINAL,ARRIVAL_TERMINAL,GATE_NO) values (117,'no',11,8,11);
Insert into PERMIT (TRIP_ID,AIRPORT_AUTHORITY,DEPARTURE_TERMINAL,ARRIVAL_TERMINAL,GATE_NO) values (118,'yes',10,6,21);
Insert into PERMIT (TRIP_ID,AIRPORT_AUTHORITY,DEPARTURE_TERMINAL,ARRIVAL_TERMINAL,GATE_NO) values (119,'YES',5,11,4);
