--------------------------------------------------------
--  File created - Sunday-June-23-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TRIP
--------------------------------------------------------

  CREATE TABLE "TRIP" 
   (	"TRIP_ID" NUMBER(3,0), 
	"FLIGHT_ID" VARCHAR2(50 BYTE), 
	"FROM_" VARCHAR2(50 BYTE), 
	"TO_" VARCHAR2(50 BYTE), 
	"TYPE_" VARCHAR2(50 BYTE), 
	"DEPARTURE" DATE, 
	"DEPART_TIME" VARCHAR2(50 BYTE), 
	"ARRIVAL_TIME" VARCHAR2(50 BYTE), 
	"DURATION_" NUMBER(2,0), 
	"STOPS" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into TRIP
SET DEFINE OFF;
Insert into TRIP (TRIP_ID,FLIGHT_ID,FROM_,TO_,TYPE_,DEPARTURE,DEPART_TIME,ARRIVAL_TIME,DURATION_,STOPS) values (204,'2A 3412','CHENNAI','MUMBAI','DOMESTIC',to_date('08-FEB-24','DD-MON-RR'),'03:00PM','07:00PM',4,0);
Insert into TRIP (TRIP_ID,FLIGHT_ID,FROM_,TO_,TYPE_,DEPARTURE,DEPART_TIME,ARRIVAL_TIME,DURATION_,STOPS) values (112,'1A 6144','DELHI','KOLKATA','DOMESTIC',to_date('07-FEB-24','DD-MON-RR'),'03:00PM','05:30PM',2,0);
Insert into TRIP (TRIP_ID,FLIGHT_ID,FROM_,TO_,TYPE_,DEPARTURE,DEPART_TIME,ARRIVAL_TIME,DURATION_,STOPS) values (113,'7F 6211','CHENNAI','DUBAI','INTERNATIONAL',to_date('12-NOV-23','DD-MON-RR'),'07:00AM','08:00PM',7,1);
Insert into TRIP (TRIP_ID,FLIGHT_ID,FROM_,TO_,TYPE_,DEPARTURE,DEPART_TIME,ARRIVAL_TIME,DURATION_,STOPS) values (114,'2A 3412','PUDUCHERRY','HYDERABAD','DOMESTIC',to_date('12-NOV-23','DD-MON-RR'),'08:00AM','11:30PM',3,1);
Insert into TRIP (TRIP_ID,FLIGHT_ID,FROM_,TO_,TYPE_,DEPARTURE,DEPART_TIME,ARRIVAL_TIME,DURATION_,STOPS) values (115,'7B 4764','GOA','MUMBAI','DOMESTIC',to_date('12-NOV-23','DD-MON-RR'),'02:00PM','04:00PM',2,0);
Insert into TRIP (TRIP_ID,FLIGHT_ID,FROM_,TO_,TYPE_,DEPARTURE,DEPART_TIME,ARRIVAL_TIME,DURATION_,STOPS) values (116,'5A 2141','DUBAI','DELHI','INTERNATIONAL',to_date('13-NOV-23','DD-MON-RR'),'05:10AM','03:10PM',8,2);
Insert into TRIP (TRIP_ID,FLIGHT_ID,FROM_,TO_,TYPE_,DEPARTURE,DEPART_TIME,ARRIVAL_TIME,DURATION_,STOPS) values (117,'3C 5271','CHENNAI','DELHI','DOMESTIC',to_date('13-NOV-23','DD-MON-RR'),'07:00AM','12:00PM',4,1);
Insert into TRIP (TRIP_ID,FLIGHT_ID,FROM_,TO_,TYPE_,DEPARTURE,DEPART_TIME,ARRIVAL_TIME,DURATION_,STOPS) values (207,'2A 3412','DELHI','KOLKATA','DOMESTIC',to_date('07-FEB-24','DD-MON-RR'),'04:00PM','08:00pm',4,1);
Insert into TRIP (TRIP_ID,FLIGHT_ID,FROM_,TO_,TYPE_,DEPARTURE,DEPART_TIME,ARRIVAL_TIME,DURATION_,STOPS) values (118,'3C 5271','CHENNAI','HYDERABAD','DOMESTIC',to_date('13-NOV-23','DD-MON-RR'),'07:00AM','09:00AM',2,0);
Insert into TRIP (TRIP_ID,FLIGHT_ID,FROM_,TO_,TYPE_,DEPARTURE,DEPART_TIME,ARRIVAL_TIME,DURATION_,STOPS) values (119,'5A 2141','DELHI','CHENNAI','DOMESTIC',to_date('14-NOV-23','DD-MON-RR'),'06:00PM','11:00PM',4,1);
Insert into TRIP (TRIP_ID,FLIGHT_ID,FROM_,TO_,TYPE_,DEPARTURE,DEPART_TIME,ARRIVAL_TIME,DURATION_,STOPS) values (200,'5A 2141','DELHI','HYDERABAD','DOMESTIC',to_date('14-NOV-23','DD-MON-RR'),'06:00PM','08:00PM',2,0);
Insert into TRIP (TRIP_ID,FLIGHT_ID,FROM_,TO_,TYPE_,DEPARTURE,DEPART_TIME,ARRIVAL_TIME,DURATION_,STOPS) values (202,'1A 6144','CHENNAI','GOA','DOMESTIC',to_date('15-NOV-23','DD-MON-RR'),'07:00AM','01:00PM',5,0);
Insert into TRIP (TRIP_ID,FLIGHT_ID,FROM_,TO_,TYPE_,DEPARTURE,DEPART_TIME,ARRIVAL_TIME,DURATION_,STOPS) values (203,'1A 6144','CHENNAI','JAIPUR','DOMESTIC',to_date('06-FEB-24','DD-MON-RR'),'04:00PM','07:00PM',3,1);
Insert into TRIP (TRIP_ID,FLIGHT_ID,FROM_,TO_,TYPE_,DEPARTURE,DEPART_TIME,ARRIVAL_TIME,DURATION_,STOPS) values (206,'2A 3412','DELHI','KOLKATA','DOMESTIC',to_date('11-NOV-23','DD-MON-RR'),'07:10AM','11:00AM',4,1);
Insert into TRIP (TRIP_ID,FLIGHT_ID,FROM_,TO_,TYPE_,DEPARTURE,DEPART_TIME,ARRIVAL_TIME,DURATION_,STOPS) values (208,'1A 6144','DELHI','KOLKATA','DOMESTIC',to_date('07-FEB-24','DD-MON-RR'),'04:00PM','07:00PM',3,0);
Insert into TRIP (TRIP_ID,FLIGHT_ID,FROM_,TO_,TYPE_,DEPARTURE,DEPART_TIME,ARRIVAL_TIME,DURATION_,STOPS) values (210,'1A 6144','CHENNAI','MUMBAI','DOMESTIC',to_date('09-JUL-24','DD-MON-RR'),'03:00PM','07:00PM',4,0);
--------------------------------------------------------
--  DDL for Trigger BEFOREDELETETRIP
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "BEFOREDELETETRIP" 
BEFORE DELETE ON TRIP
FOR EACH ROW
DECLARE
    v_e_price NUMBER(6);
    v_b_price NUMBER(6);
    v_f_price NUMBER(6);
BEGIN
    INSERT INTO BAK (TRIP_ID, FLIGHT_ID, FROM_, TO_, TYPE_, DEPARTURE, DEPART_TIME, ARRIVAL_TIME, DURATION_, STOPS, E_PRICE, B_PRICE, F_PRICE)
    SELECT
        :OLD.TRIP_ID,
        :OLD.FLIGHT_ID,
        :OLD.FROM_,
        :OLD.TO_,
        :OLD.TYPE_,
        :OLD.DEPARTURE,
        :OLD.DEPART_TIME,
        :OLD.ARRIVAL_TIME,
        :OLD.DURATION_,
        :OLD.STOPS,
        S.E_PRICE,
        S.B_PRICE,
        S.F_PRICE
    FROM
        SEATS S
    WHERE
        S.TRIP_ID = :OLD.TRIP_ID;

    DELETE FROM SEATS WHERE TRIP_ID = :OLD.TRIP_ID;
END BeforeDeleteTrip;

/
ALTER TRIGGER "BEFOREDELETETRIP" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_DELETE_SEATS
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_DELETE_SEATS" 
AFTER DELETE ON TRIP
FOR EACH ROW
BEGIN
    DELETE FROM SEATS WHERE TRIP_ID = :OLD.TRIP_ID;
END;

/
ALTER TRIGGER "TRG_DELETE_SEATS" ENABLE;
